In [1]:
from read_graph import read_ID_map, read_link_graph
from helpers import build_transpose_graph

TITLES_TO_IDS, IDS_TO_TILES = read_ID_map("data/ID_map.txt")
GRAPH = read_link_graph("data/link_graph_ids.txt")
NUM_PAGES = len(GRAPH)

Reading Graph: 100%|██████████| 16833643/16833643 [00:43<00:00, 389810.17it/s]


In [105]:
# compute distance TO the landmarks
TRANSPOSE_GRAPH = build_transpose_graph(GRAPH)

Building Transpose Graph:  89%|████████▉ | 14837196/16714619 [01:28<00:09, 201461.92it/s]

In [95]:
NUM_PAGES

16714619

In [100]:
from collections import deque
import numpy as np


def get_distances_BFS(start, graph=GRAPH):
    distances = np.zeros(NUM_PAGES)
    distances.fill(np.nan)

    queue = deque()
    queue.append(start)
    distances[start] = 0

    queued = set()
    num_visited = 0

    while queue:
        curr = queue.popleft()
        # if curr in visited: continue

        assert(not np.isnan(distances[curr]))
        # print(curr, distances[curr])

        num_visited += 1

        if num_visited % 500_000 == 0:
            print(num_visited)
            # break   # TESTING

        for link in graph[curr]:
            if link in queued: continue
            
            queue.append(link)
            # print(curr, link)
            distances[link] = distances[curr] + 1

            queued.add(link)

    return distances


In [113]:
NUM_LANDMARKS = 15
LANDMARKS = [TITLES_TO_IDS["Pittsburgh"]]

DISTANCES = np.array([
    get_distances_BFS(LANDMARKS[0]),
])


for _ in range(NUM_LANDMARKS-1):
    print(DISTANCES.shape)
    assert(len(DISTANCES.shape) == 2)
    for row in DISTANCES:
        print(row[~np.isnan(row)])

    shortest_distances = np.nanmin(DISTANCES, axis=0)

    print(shortest_distances[~np.isnan(shortest_distances)])
    next_landmark = np.nanargmax(shortest_distances)

    print("next_landmark:", IDS_TO_TILES[next_landmark])
    print("distance from all previously chosen landmarks:", shortest_distances[next_landmark])

    LANDMARKS.append(next_landmark)
    DISTANCES = np.append(DISTANCES, [get_distances_BFS(next_landmark)], axis=0)



500000
1000000
1500000
2000000
2500000
3000000
3500000
4000000
4500000
5000000
5500000
6000000
6500000
7000000
7500000
8000000
8500000
9000000
(1, 16714619)
[2. 2. 3. ... 3. 3. 4.]


/var/folders/j3/_k92zpq172d0p68rq5kvdbsc0000gn/T/ipykernel_54043/307694363.py:15: RuntimeWarning: All-NaN slice encountered
  shortest_distances = np.nanmin(DISTANCES, axis=0)


[2. 2. 3. ... 3. 3. 4.]
next_landmark: List_of_highways_numbered_1187
distance from all previously chosen landmarks: 103.0
500000
1000000
1500000
2000000
2500000
3000000
3500000
4000000
4500000
5000000
5500000
6000000
6500000
7000000
7500000
8000000
8500000
9000000
(2, 16714619)
[2. 2. 3. ... 3. 3. 4.]
[64. 64. 64. ... 64. 65. 66.]
[2. 2. 3. ... 3. 3. 4.]
next_landmark: Parmouti_12
distance from all previously chosen landmarks: 94.0
500000
1000000
1500000
2000000
2500000
3000000
3500000
4000000
4500000
5000000
5500000
6000000
6500000
7000000
7500000
8000000
8500000
9000000
(3, 16714619)
[2. 2. 3. ... 3. 3. 4.]
[64. 64. 64. ... 64. 65. 66.]
[3. 4. 4. ... 4. 4. 6.]
[2. 2. 3. ... 3. 3. 4.]
next_landmark: List_of_highways_numbered_1054
distance from all previously chosen landmarks: 59.0
500000
1000000
1500000
2000000
2500000
3000000
3500000
4000000
4500000
5000000
5500000
6000000
6500000
7000000
7500000
8000000
8500000
9000000
(4, 16714619)
[2. 2. 3. ... 3. 3. 4.]
[64. 64. 64. ... 64. 65. 

In [114]:
for l in LANDMARKS:
    print(IDS_TO_TILES[l])

Pittsburgh
List_of_highways_numbered_1187
Parmouti_12
List_of_highways_numbered_1054
List_of_highways_numbered_1135
Hathor_25
Meshir_25
1968_Liga_Deportiva_Universitaria_de_Quito_season
Papyrus_Oxyrhynchus_158
Thout_1
1958_São_Paulo_FC_season
List_of_highways_numbered_1056
1959_NCAA_University_Division_baseball_rankings
List_of_peers_1580–1589
List_of_peers_1580–1589


In [115]:
TRANSPOSE_DISTANCES = np.array([
    get_distances_BFS(landmark, TRANSPOSE_GRAPH)
    for landmark in LANDMARKS
])

assert(TRANSPOSE_DISTANCES.shape == DISTANCES.shape)

500000
1000000
1500000
2000000
2500000
3000000
3500000
4000000
4500000
5000000
5500000
6000000
6500000
7000000
7500000
8000000
8500000
9000000
9500000
10000000
10500000
11000000
11500000
12000000
12500000
13000000
13500000
14000000
14500000
15000000
15500000
500000
1000000
1500000
2000000
2500000
3000000
3500000
4000000
4500000
5000000
5500000
6000000
6500000
7000000
7500000
8000000
8500000
9000000
9500000
10000000
10500000
11000000
11500000
12000000
12500000
13000000
13500000
14000000
14500000
15000000
15500000
500000
1000000
1500000
2000000
2500000
3000000
3500000
4000000
4500000
5000000
5500000
6000000
6500000
7000000
7500000
8000000
8500000
9000000
9500000
10000000
10500000
11000000
11500000
12000000
12500000
13000000
13500000
14000000
14500000
15000000
15500000
500000
1000000
1500000
2000000
2500000
3000000
3500000
4000000
4500000
5000000
5500000
6000000
6500000
7000000
7500000
8000000
8500000
9000000
9500000
10000000
10500000
11000000
11500000
12000000
12500000
13000000
13500000


In [116]:
np.savez(
    "landmarks.npz",
    landmarks=LANDMARKS,
    from_distances=DISTANCES,
    to_distances=TRANSPOSE_DISTANCES
)

In [117]:
data = np.load("landmarks.npz")
print(data["landmarks"])
print(data["from_distances"])
print(data["to_distances"])
data.close()

[   16306 14659163 15142548 14605757 14657914 15092706 15141787 11623005
  6973277 15089553 10742367 11329689  7456022  8309479  8309479]
[[nan  2. nan ...  4. nan nan]
 [nan 64. nan ... 66. nan nan]
 [nan  3. nan ...  6. nan nan]
 ...
 [nan  3. nan ...  5. nan nan]
 [nan  3. nan ...  6. nan nan]
 [nan  3. nan ...  6. nan nan]]
[[  3.   2.   3. ...   3.   4.   4.]
 [104. 103. 103. ... 104. 104. 105.]
 [ 96.  95.  96. ...  97.  97.  97.]
 ...
 [ 38.  37.  38. ...  38.  37.  38.]
 [ 33.  31.  32. ...  33.  33.  33.]
 [ 33.  31.  32. ...  33.  33.  33.]]
